### PR TITLE
configure service for embedded prometheus exporter

### PR DESCRIPTION
**Pull request by BDelacour**
Hi !

I don't know if it is the best way to do this but let me know if you want me to change some things

### CODE REVIEW

**Comment by fraenki** [comment]
@BDelacour Would you please have a look at the test failures? I'd recommend to run `pdk validate` and `pdk test unit` locally.

**Comment by BDelacour** [comment]
> @BDelacour Would you please have a look at the test failures? I'd recommend to run `pdk validate` and `pdk test unit` locally.

~I did it and it was ok.~ I'll have a look

I forgot to do it before a last minute commit. It should be ok :)

**Comment by BDelacour** [comment]
@fraenki I investigated the el7 problem.

The `solr-exporter` service can't start because the script uses `which` (https://github.com/apache/solr/blob/main/solr/prometheus-exporter/bin/solr-exporter#L61) and it is not present by default in el7.
I tested to install it with `yum install which` and it was good.

I see two solutions : 
- Install `which` but it means adding the `package` (https://forge.puppet.com/modules/puppetlabs/package/readme) module as dependency
- `which` is called because I'm not specifying a `JAVA_HOME`(https://github.com/apache/solr/blob/main/solr/prometheus-exporter/bin/solr-exporter#L53), I could try to add a standard one

Which solution do you prefer ? (the second looks like a "hack" for me, but the first is a bit fat for this little problem)

**Comment by BDelacour** [comment]
Hello @fraenki, a little UP so this PR is not forgotten :)

I left a comment some days ago which requires your attention

Thank you !

**Comment by fraenki** [comment]
Merged, thank you! Sorry that it took me so long, btw... :-/

**Comment by fraenki** [comment]
Available in version 4.0.0:
https://forge.puppet.com/modules/markt/solr/changelog

**Pull request merged**
